version: "3.5"
services:
  ${repository}:
    image: hatlonely/${repository}:${version}
    hostname: ${repository}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6000:80"
    volumes:
      - "/var/docker/${repository}/log:/var/log/nginx"
      - "/var/docker/${repository}/run:/var/run"
    networks:
      - ${repository}net
      - kibananet
      - grafananet
      - jenkinsnet
      - wordpressnet
      - chronografnet
      - portainernet
      - vue-accountnet
      - vue-toolnet
      - vue-ancientnet
      - vue-gamenet
      - vue-technet
      - go-accountnet
      - go-cloudnet
      - go-ancientnet
      - go-technet
networks:
  ${repository}net:
    name: ${repository}net
  kibananet:
    external: true
    name: kibananet
  grafananet:
    external: true
    name: grafananet
  jenkinsnet:
    external: true
    name: jenkinsnet
  wordpressnet:
    external: true
    name: wordpressnet
  chronografnet:
    external: true
    name: chronografnet
  portainernet:
    external: true
    name: portainernet
  vue-accountnet:
    external: true
    name: vue-accountnet
  vue-toolnet:
    external: true
    name: vue-toolnet
  vue-ancientnet:
    external: true
    name: vue-ancientnet
  vue-gamenet:
    external: true
    name: vue-gamenet
  vue-technet:
    external: true
    name: vue-technet
  go-accountnet:
    external: true
    name: go-accountnet
  go-cloudnet:
    external: true
    name: go-cloudnet
  go-ancientnet:
    external: true
    name: go-ancientnet
  go-technet:
    external: true
    name: go-technet
