version: "3.5"
services:
  ${repository}:
    image: hatlonely/${repository}:${version}
    hostname: ${repository}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6000:80"
    volumes:
      - "/var/docker/${repository}/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "/var/docker/${repository}/conf/conf.d:/etc/nginx/conf.d"
      - "/var/docker/${repository}/log:/var/log/nginx"
      - "/var/docker/${repository}/run:/var/run"
    networks:
      - online
networks:
  online:
    external: true
    name: online
